### ISSUE TITLE
Change the UI to match the provided designs.

### ISSUE THREAD

**Issue by davidnjau** [IntelliSOFT-Consulting/human-milk-bank#3]
## 1. Feature proposal 

**Problem to solve**
The initial app has a different UI from the provided UI wireframes.

**Proposal**
Implement the UI as per the designs. 

**Further details**
- The walkthrough screens
- Splash Screens
- Login Page, and any other colours

**Comment by Itskiprotich** [comment]
Login Page UI aligned to the design
